### ISSUE TITLE
How to decode memento

### ISSUE THREAD

**Issue by upoque** [swsnu/bd2017#7]
Task의 call()함수에서 memento 를 decode하는데 애를 먹고 있습니다..
int idx = 0
...
.set(TaskConfiguration.MEMENTO, String.valueOf(idx))
...
으로 memento 를 설정했습니다.

수업 시간에서는 
final String mementoStr = new String(memento)
을 이용해서 이 값을 사용하시던데 해보았지만 아무런 값이 나오지 않습니다..

byte[] valueDecoded= Base64.decodeBase64(memento);
String s = new String(valueDecoded)
와 같은 방법을 사용해도 역시 아무런 데이터가 나오지 않습니다.

Task의 call함수에서 System.out.println(memento)를 하게 되면
[B@293796aa 등과 같이뜨는것을 보아, 뭔가 전달이 되긴 되는것 같습니다.

어떻게 memento를 사용할 수 있을까요?

**Comment by yunseong** [comment]
안녕하세요.
REEF code repository의 Suspend example (https://github.com/apache/reef/blob/master/lang/java/reef-examples/src/main/java/org/apache/reef/examples/suspend/SuspendDriver.java, https://github.com/apache/reef/blob/master/lang/java/reef-examples/src/main/java/org/apache/reef/examples/suspend/SuspendTestTask.java)을 보시면 Driver와 Task 사이에 message 주고 받는 부분을 참조하실 수 있습니다.

`new String()`이 좀 더 단순한 것으로 보여서 수업시간에 시도해 보았으나 해당 API는 그렇게 사용하면 안되는 것 같습니다.
말씀은 드렸었는데 잘 전달이 되지 않은 것 같습니다. 혼동을 드려 죄송합니다.

**Comment by DopingDeveloper** [comment]
해당 부분을 지속적으로 구현해보려고 하는데요.
우선 SuspendtestTask에서 사용한 WritableCodec을 제 프로젝트에서 구현하려고 했으나,
hadoop package를 import하지를 못하더라구요.
또한 해당 예제를 보면 memento를 restore해서 채널을 만들어서 읽고,
그 값으로 쓰는데.. 굳이 채널까지 만들어주면서 해야하는지도 궁금합니다.

**Comment by gyeongin** [comment]
Memento를 task configuration에 bind 해 줄때, byte array를 String으로 바꿔야 하는데,
어딘가의 예제에서 `javax.xml.bind.DatatypeConverter.printBase64Binary()`를 사용하는것을 보았습니다. 이걸 사용하지 않아서 생긴 문제인지는 모르겠지만요 :)

**Comment by DopingDeveloper** [comment]
@gyeongin 해당 부분은 Driver에서 설정해주었습니다.
Task쪽에서 읽어오는 부분이 문제가 되는 상황이라서요..
예제에서처럼 private 변수와 memento 간에 채널을 만들고 read로 덮어씌우기를 하던가 해야하는 것 같은데
해결 방법이 도저히 나오질 않네요.

**Comment by gyeongin** [comment]
저는 `java.io.DataInputStream.readDouble()`로 `byte[] memento`를 double array로 parse했습니다.
예제에서처럼 ByteBuffer를 쓰셔도 잘 동작할 것 같습니다. 굳이 channel을 만들 필요는 없고, 내부적으로 byte array를 buffer로 가지고 double을 parse해 줄 수 있는 object이기만 하면 될것 같습니다.
`ByteBuffer.wrap(...).asDoubleBuffer().array()`로 하셔도 될 것 같고요

**Comment by DopingDeveloper** [comment]
음.. 방금 String instance로 테스트 해봤는데요.
`private static final ObjectSerializableCodec<String> CODEC = new ObjectSerializableCodec<>();` 을 Driver랑 Task에 선언해주시고, Driver에서는 MEMENTO로 넣어줄 때 `CODEC.encode` 해서 넣어주고, Task에서는 `CODEC.decode(memento)` 하니까 되네요..!

**Comment by upoque** [comment]
위방법처럼 CODEC을 만들어주어 해결했습니다. 감사합니다^^.
